<%@ Page Title="" Language="C#" MasterPageFile="~/UserPage.Master" AutoEventWireup="true" CodeBehind="Dashboard.aspx.cs" Inherits="SkillSage.Dashboard" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="sidebar">
        <a href="Dashboard.aspx">Home</a>
        <a href="UserDetails.aspx">Details</a>
        <a href="UserProfile.aspx">Profile</a>
        <asp:LinkButton ID="LinkButton1" runat="server" OnClick="session_back">Log Out</asp:LinkButton>

    </div>
    <div class="content">
        <div class="welcome-message">
            HELLO, WELCOME TO THE 
        </div>
        <div class="grid-container">
            <h2>User Information</h2>
            <asp:GridView ID="GridView1" runat="server" OnRowDataBound="GridView1_RowDataBound" CssClass="grid" DataSourceID="SqlDataSource1" GridLines="None" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
                <HeaderStyle CssClass="grid-header" />
                <RowStyle CssClass="grid-row" />
                <FooterStyle CssClass="grid-footer" />
            </asp:GridView>
        </div>
    </div>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:skillsage %>"
        DeleteCommand="DELETE FROM [employee] WHERE [Id] = @Id"
        InsertCommand="INSERT INTO [employee] ([name], [emailid], [gender], [userid], [role], [password]) VALUES (@name, @emailid, @gender, @userid, @role, @password)"
        SelectCommand="SELECT * FROM [employee]"
        UpdateCommand="UPDATE [employee] SET [name] = @name, [emailid] = @emailid, [gender] = @gender, [userid] = @userid, [role] = @role, [password] = @password WHERE [Id] = @Id">
        <DeleteParameters>
            <asp:Parameter Name="Id" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="name" Type="String" />
            <asp:Parameter Name="email" Type="String" />
            <asp:Parameter Name="gender" Type="String" />
            <asp:Parameter Name="userid" Type="String" />
            <asp:Parameter Name="role" Type="String" />
            <asp:Parameter Name="password" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="name" Type="String" />
            <asp:Parameter Name="email" Type="String" />
            <asp:Parameter Name="gender" Type="String" />
            <asp:Parameter Name="userid" Type="String" />
            <asp:Parameter Name="role" Type="String" />
            <asp:Parameter Name="password" Type="String" />
            <asp:Parameter Name="Id" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
</asp:Content>
